{
  "openapi": "3.0.1",
  "info": {
    "title": "Voglander",
    "description": "",
    "version": "1.0.0"
  },
  "tags": [],
  "paths": {
    "/zlm/api/version": {
      "get": {
        "summary": "获取版本信息",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ServerResponseVersion"
                },
                "example": {
                  "code": 0,
                  "data": {
                    "buildTime": "",
                    "branchName": "",
                    "commitHash": ""
                  },
                  "msg": "",
                  "result": ""
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/zlm/api/api/list": {
      "get": {
        "summary": "获取API列表",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": "key",
            "in": "query",
            "description": "",
            "required": false,
            "schema": {
              "type": ""
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ServerResponseListString"
                },
                "example": {
                  "code": 0,
                  "data": [""],
                  "msg": "",
                  "result": ""
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/zlm/api/threads/load": {
      "get": {
        "summary": "获取网络线程负载",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ServerResponseListThreadLoad"
                },
                "example": {
                  "code": 0,
                  "data": [
                    {
                      "delay": "",
                      "load": ""
                    }
                  ],
                  "msg": "",
                  "result": ""
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/zlm/api/statistic": {
      "get": {
        "summary": "获取主要对象个数",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ServerResponseImportantObjectNum"
                },
                "example": {
                  "code": 0,
                  "data": {
                    "Buffer": 0,
                    "RtpPacket": 0,
                    "Frame": 0,
                    "RtmpPacket": 0,
                    "TcpSession": 0,
                    "UdpServer": 0,
                    "TcpServer": 0,
                    "FrameImp": 0,
                    "BufferList": 0,
                    "BufferRaw": 0,
                    "MediaSource": 0,
                    "MultiMediaSourceMuxer": 0,
                    "TcpClient": 0,
                    "BufferLikeString": 0,
                    "Socket": 0,
                    "UdpSession": 0
                  },
                  "msg": "",
                  "result": ""
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/zlm/api/work-threads/load": {
      "get": {
        "summary": "获取后台线程负载",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ServerResponseListThreadLoad"
                },
                "example": {
                  "code": 0,
                  "data": [
                    {
                      "delay": "",
                      "load": ""
                    }
                  ],
                  "msg": "",
                  "result": ""
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/zlm/api/server/config": {
      "get": {
        "summary": "获取服务器配置",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ServerResponseListServerNodeConfig"
                },
                "example": {
                  "code": 0,
                  "data": {
                    "rtp.rtpMaxSize": "",
                    "protocol.hls_demand": "",
                    "rtp_proxy.opus_pt": "",
                    "rtp_proxy.timeoutSec": "",
                    "rtmp.port": "",
                    "hook.on_ip_not_found": "",
                    "record.fileRepeat": "",
                    "general.flowThreshold": "",
                    "rtsp.rtpTransportType": "",
                    "hook.retry_delay": "",
                    "http.rootPath": "",
                    "rtsp.keepAliveSecond": "",
                    "hook.on_server_started": "",
                    "api.defaultSnap": "",
                    "cluster.origin_url": "",
                    "http.port": "",
                    "http.virtualPath": "",
                    "http.keepAliveSecond": "",
                    "ffmpeg.log": "",
                    "hook.on_flow_report": "",
                    "http.dirMenu": "",
                    "rtsp.directProxy": "",
                    "ffmpeg.cmd": "",
                    "rtp.lowLatency": "",
                    "protocol.enable_rtsp": "",
                    "rtsp.port": "",
                    "rtmp.sslport": "",
                    "protocol.hls_save_path": "",
                    "http.charSet": "",
                    "http.sendBufSize": "",
                    "hls.broadcastRecordTs": "",
                    "api.apiDebug": "",
                    "general.mergeWriteMS": "",
                    "http.forbidCacheSuffix": "",
                    "http.notFound": "",
                    "hook.retry": "",
                    "record.appName": "",
                    "hls.fileBufSize": "",
                    "hook.timeoutSec": "",
                    "rtsp.sslport": "",
                    "hls.deleteDelaySec": "",
                    "hook.on_rtp_server_timeout": "",
                    "hook.on_send_rtp_stopped": "",
                    "hook.on_record_mp4": "",
                    "hook.alive_interval": "",
                    "rtmp.handshakeSecond": "",
                    "hook.stream_changed_schemas": "",
                    "rtc.externIP": "",
                    "rtc.rembBitRate": "",
                    "general.streamNoneReaderDelayMS": "",
                    "protocol.mp4_max_second": "",
                    "hook.on_publish": "",
                    "rtp_proxy.port": "",
                    "http.sslport": "",
                    "rtp.audioMtuSize": "",
                    "general.check_nvidia_dev": "",
                    "record.fastStart": "",
                    "hook.on_stream_not_found": "",
                    "rtp_proxy.port_range": "",
                    "protocol.enable_rtmp": "",
                    "srt.timeoutSec": "",
                    "rtsp.handshakeSecond": "",
                    "hls.segDur": "",
                    "protocol.mp4_as_player": "",
                    "api.secret": "",
                    "hls.segRetain": "",
                    "protocol.rtsp_demand": "",
                    "srt.port": "",
                    "srt.pktBufSize": "",
                    "rtp_proxy.gop_cache": "",
                    "shell.maxReqSize": "",
                    "ffmpeg.snap": "",
                    "general.maxStreamWaitMS": "",
                    "multicast.addrMax": "",
                    "general.wait_add_track_ms": "",
                    "http.allow_cross_domains": "",
                    "protocol.modify_stamp": "",
                    "rtp.videoMtuSize": "",
                    "api.snapRoot": "",
                    "protocol.enable_audio": "",
                    "hook.on_server_keepalive": "",
                    "multicast.addrMin": "",
                    "protocol.ts_demand": "",
                    "protocol.enable_fmp4": "",
                    "rtsp.lowLatency": "",
                    "http.allow_ip_range": "",
                    "hook.on_rtsp_realm": "",
                    "hook.on_stream_changed": "",
                    "http.forwarded_ip_header": "",
                    "rtp_proxy.h265_pt": "",
                    "hook.on_del_mp4": "",
                    "protocol.enable_hls": "",
                    "protocol.enable_mp4": "",
                    "rtc.port": "",
                    "protocol.fmp4_demand": "",
                    "record.sampleMS": "",
                    "shell.port": "",
                    "hook.on_shell_login": "",
                    "cluster.retry_count": "",
                    "general.enableVhost": "",
                    "general.unready_frame_cache": "",
                    "rtc.preferredCodecV": "",
                    "rtp_proxy.h264_pt": "",
                    "protocol.auto_close": "",
                    "srt.latencyMul": "",
                    "hook.on_server_exited": "",
                    "general.resetWhenRePlay": "",
                    "protocol.mp4_save_path": "",
                    "protocol.continue_push_ms": "",
                    "rtp_proxy.dumpDir": "",
                    "rtp_proxy.ps_pt": "",
                    "hook.enable": "",
                    "rtc.timeoutSec": "",
                    "rtc.preferredCodecA": "",
                    "hls.segKeep": "",
                    "multicast.udpTTL": "",
                    "rtp.h264_stap_a": "",
                    "hook.on_stream_none_reader": "",
                    "hook.on_record_ts": "",
                    "ffmpeg.bin": "",
                    "protocol.enable_ts": "",
                    "protocol.enable_hls_fmp4": "",
                    "hls.segNum": "",
                    "http.maxReqSize": "",
                    "rtc.tcpPort": "",
                    "cluster.timeout_sec": "",
                    "general.enable_ffmpeg_log": "",
                    "general.mediaServerId": "",
                    "hook.on_http_access": "",
                    "general.wait_track_ready_ms": "",
                    "rtsp.authBasic": "",
                    "hook.on_rtsp_auth": "",
                    "protocol.rtmp_demand": "",
                    "protocol.add_mute_audio": "",
                    "record.fileBufSize": "",
                    "rtmp.keepAliveSecond": "",
                    "hook.on_play": ""
                  },
                  "msg": "",
                  "result": ""
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    }
  },
  "components": {
    "schemas": {
      "Version": {
        "type": "object",
        "properties": {
          "buildTime": {
            "type": "string",
            "description": ""
          },
          "branchName": {
            "type": "string",
            "description": ""
          },
          "commitHash": {
            "type": "string",
            "description": ""
          }
        }
      },
      "ServerResponseVersion": {
        "type": "object",
        "properties": {
          "code": {
            "type": "integer",
            "description": ""
          },
          "data": {
            "$ref": "#/components/schemas/Version",
            "description": ""
          },
          "msg": {
            "type": "string",
            "description": "",
            "default": "success"
          },
          "result": {
            "type": "string",
            "description": "",
            "default": "success"
          }
        }
      },
      "ServerResponseListString": {
        "type": "object",
        "properties": {
          "code": {
            "type": "integer",
            "description": ""
          },
          "data": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": ""
          },
          "msg": {
            "type": "string",
            "description": "",
            "default": "success"
          },
          "result": {
            "type": "string",
            "description": "",
            "default": "success"
          }
        }
      },
      "ThreadLoad": {
        "type": "object",
        "properties": {
          "delay": {
            "type": "string",
            "description": "该线程延时"
          },
          "load": {
            "type": "string",
            "description": "该线程负载，0 ~ 100"
          }
        }
      },
      "ServerResponseListThreadLoad": {
        "type": "object",
        "properties": {
          "code": {
            "type": "integer",
            "description": ""
          },
          "data": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/ThreadLoad",
              "description": ""
            },
            "description": ""
          },
          "msg": {
            "type": "string",
            "description": "",
            "default": "success"
          },
          "result": {
            "type": "string",
            "description": "",
            "default": "success"
          }
        }
      },
      "ServerResponseImportantObjectNum": {
        "type": "object",
        "properties": {
          "code": {
            "type": "integer",
            "description": ""
          },
          "data": {
            "$ref": "#/components/schemas/ImportantObjectNum",
            "description": ""
          },
          "msg": {
            "type": "string",
            "description": "",
            "default": "success"
          },
          "result": {
            "type": "string",
            "description": "",
            "default": "success"
          }
        }
      },
      "ImportantObjectNum": {
        "type": "object",
        "properties": {
          "Buffer": {
            "type": "integer",
            "description": ""
          },
          "RtpPacket": {
            "type": "integer",
            "description": ""
          },
          "Frame": {
            "type": "integer",
            "description": ""
          },
          "RtmpPacket": {
            "type": "integer",
            "description": ""
          },
          "TcpSession": {
            "type": "integer",
            "description": ""
          },
          "UdpServer": {
            "type": "integer",
            "description": ""
          },
          "TcpServer": {
            "type": "integer",
            "description": ""
          },
          "FrameImp": {
            "type": "integer",
            "description": ""
          },
          "BufferList": {
            "type": "integer",
            "description": ""
          },
          "BufferRaw": {
            "type": "integer",
            "description": ""
          },
          "MediaSource": {
            "type": "integer",
            "description": ""
          },
          "MultiMediaSourceMuxer": {
            "type": "integer",
            "description": ""
          },
          "TcpClient": {
            "type": "integer",
            "description": ""
          },
          "BufferLikeString": {
            "type": "integer",
            "description": ""
          },
          "Socket": {
            "type": "integer",
            "description": ""
          },
          "UdpSession": {
            "type": "integer",
            "description": ""
          }
        }
      },
      "ServerResponseListServerNodeConfig": {
        "type": "object",
        "properties": {
          "code": {
            "type": "integer",
            "description": ""
          },
          "data": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/ServerNodeConfig",
              "description": "io.github.lunasaw.zlm.entity.ServerNodeConfig"
            },
            "description": ""
          },
          "msg": {
            "type": "string",
            "description": "",
            "default": "success"
          },
          "result": {
            "type": "string",
            "description": "",
            "default": "success"
          }
        }
      },
      "ServerNodeConfig": {
        "type": "object",
        "properties": {
          "rtp.rtpMaxSize": {
            "type": "string",
            "description": "The maximum size of RTP packets."
          },
          "protocol.hls_demand": {
            "type": "string",
            "description": "Whether to enable HLS demand."
          },
          "rtp_proxy.opus_pt": {
            "type": "string",
            "description": "The Opus payload type used by the RTP proxy."
          },
          "rtp_proxy.timeoutSec": {
            "type": "string",
            "description": "The timeout value for the RTP proxy in seconds."
          },
          "rtmp.port": {
            "type": "string",
            "description": "The port used for RTMP."
          },
          "hook.on_ip_not_found": {
            "type": "string",
            "description": "The action to take when the IP address is not found."
          },
          "record.fileRepeat": {
            "type": "string",
            "description": "Whether to allow file repetition during recording."
          },
          "general.flowThreshold": {
            "type": "string",
            "description": "The threshold for the maximum flow."
          },
          "rtsp.rtpTransportType": {
            "type": "string",
            "description": "The transport type used for RTP in RTSP."
          },
          "hook.retry_delay": {
            "type": "string",
            "description": "The delay time for retrying hooks in seconds."
          },
          "http.rootPath": {
            "type": "string",
            "description": "The root path for HTTP requests."
          },
          "rtsp.keepAliveSecond": {
            "type": "string",
            "description": "The time in seconds to keep the RTSP connection alive."
          },
          "hook.on_server_started": {
            "type": "string",
            "description": "The action to take when the server is started."
          },
          "api.defaultSnap": {
            "type": "string",
            "description": "The default snapshot for the API."
          },
          "cluster.origin_url": {
            "type": "string",
            "description": "The origin URL for the cluster."
          },
          "http.port": {
            "type": "string",
            "description": "The port used for HTTP."
          },
          "http.virtualPath": {
            "type": "string",
            "description": "The virtual path for HTTP requests."
          },
          "http.keepAliveSecond": {
            "type": "string",
            "description": "The time in seconds to keep the HTTP connection alive."
          },
          "ffmpeg.log": {
            "type": "string",
            "description": "The log file for FFmpeg."
          },
          "hook.on_flow_report": {
            "type": "string",
            "description": "The action to take when a flow report is received."
          },
          "http.dirMenu": {
            "type": "string",
            "description": "Whether to enable directory listing for HTTP requests."
          },
          "rtsp.directProxy": {
            "type": "string",
            "description": "Whether to use direct proxy for RTSP."
          },
          "ffmpeg.cmd": {
            "type": "string",
            "description": "The command used for FFmpeg."
          },
          "rtp.lowLatency": {
            "type": "string",
            "description": "Whether to enable low latency for RTP."
          },
          "protocol.enable_rtsp": {
            "type": "string",
            "description": "Whether to enable RTSP."
          },
          "rtsp.port": {
            "type": "string",
            "description": "The port used for RTSP."
          },
          "rtmp.sslport": {
            "type": "string",
            "description": "The SSL port used for RTMP."
          },
          "protocol.hls_save_path": {
            "type": "string",
            "description": "The save path for HLS."
          },
          "http.charSet": {
            "type": "string",
            "description": "The character set used for HTTP requests."
          },
          "http.sendBufSize": {
            "type": "string",
            "description": "The size of the send buffer for HTTP requests."
          },
          "hls.broadcastRecordTs": {
            "type": "string",
            "description": "Whether to broadcast recorded TS files."
          },
          "api.apiDebug": {
            "type": "string",
            "description": "Whether to enable API debugging."
          },
          "general.mergeWriteMS": {
            "type": "string",
            "description": "The time in milliseconds for merging writes."
          },
          "http.forbidCacheSuffix": {
            "type": "string",
            "description": "The suffixes to forbid caching for HTTP requests."
          },
          "http.notFound": {
            "type": "string",
            "description": "The action to take when a resource is not found for HTTP requests."
          },
          "hook.retry": {
            "type": "string",
            "description": "The number of times to retry hooks."
          },
          "record.appName": {
            "type": "string",
            "description": "The application name for recording."
          },
          "hls.fileBufSize": {
            "type": "string",
            "description": "The buffer size for HLS files."
          },
          "hook.timeoutSec": {
            "type": "string",
            "description": "The timeout value for hooks in seconds."
          },
          "rtsp.sslport": {
            "type": "string",
            "description": "The SSL port used for RTSP."
          },
          "hls.deleteDelaySec": {
            "type": "string",
            "description": "The delay time for deleting HLS files in seconds."
          },
          "hook.on_rtp_server_timeout": {
            "type": "string",
            "description": "The action to take when the RTP server times out."
          },
          "hook.on_send_rtp_stopped": {
            "type": "string",
            "description": "The action to take when sending RTP is stopped."
          },
          "hook.on_record_mp4": {
            "type": "string",
            "description": "The action to take when recording MP4 files."
          },
          "hook.alive_interval": {
            "type": "string",
            "description": "The interval time for sending keepalive messages for hooks in seconds."
          },
          "rtmp.handshakeSecond": {
            "type": "string",
            "description": "The time in seconds for the RTMP handshake."
          },
          "hook.stream_changed_schemas": {
            "type": "string",
            "description": "The schemas to use for stream changes in hooks."
          },
          "rtc.externIP": {
            "type": "string",
            "description": "The external IP address for RTC."
          },
          "rtc.rembBitRate": {
            "type": "string",
            "description": "The bit rate for REMB in RTC."
          },
          "general.streamNoneReaderDelayMS": {
            "type": "string",
            "description": "The time in milliseconds for waiting for a stream reader."
          },
          "protocol.mp4_max_second": {
            "type": "string",
            "description": "The maximum duration for MP4 files in seconds."
          },
          "hook.on_publish": {
            "type": "string",
            "description": "The action to take when publishing a stream."
          },
          "rtp_proxy.port": {
            "type": "string",
            "description": "The port used for the RTP proxy."
          },
          "http.sslport": {
            "type": "string",
            "description": "The SSL port used for HTTP."
          },
          "rtp.audioMtuSize": {
            "type": "string",
            "description": "The MTU size for audio packets in RTP."
          },
          "general.check_nvidia_dev": {
            "type": "string",
            "description": "Whether to check for NVIDIA devices."
          },
          "record.fastStart": {
            "type": "string",
            "description": "Whether to enable fast start for recording."
          },
          "hook.on_stream_not_found": {
            "type": "string",
            "description": "The action to take when a stream is not found in hooks."
          },
          "rtp_proxy.port_range": {
            "type": "string",
            "description": "The port range used for the RTP proxy."
          },
          "protocol.enable_rtmp": {
            "type": "string",
            "description": "Whether to enable RTMP."
          },
          "srt.timeoutSec": {
            "type": "string",
            "description": "The timeout value for SRT in seconds."
          },
          "rtsp.handshakeSecond": {
            "type": "string",
            "description": "The time in seconds for the RTSP handshake."
          },
          "hls.segDur": {
            "type": "string",
            "description": "The duration for each HLS segment in seconds."
          },
          "protocol.mp4_as_player": {
            "type": "string",
            "description": "Whether to use MP4 as a player for the protocol."
          },
          "api.secret": {
            "type": "string",
            "description": "The secret key for the API."
          },
          "hls.segRetain": {
            "type": "string",
            "description": "The number of HLS segments to retain."
          },
          "protocol.rtsp_demand": {
            "type": "string",
            "description": "Whether to enable demand for RTSP."
          },
          "srt.port": {
            "type": "string",
            "description": "The port used for SRT."
          },
          "srt.pktBufSize": {
            "type": "string",
            "description": "The packet buffer size for SRT."
          },
          "rtp_proxy.gop_cache": {
            "type": "string",
            "description": "Whether to enable GOP caching for the RTP proxy."
          },
          "shell.maxReqSize": {
            "type": "string",
            "description": "The maximum size of requests for the shell."
          },
          "ffmpeg.snap": {
            "type": "string",
            "description": "Whether to enable snapshots for FFmpeg."
          },
          "general.maxStreamWaitMS": {
            "type": "string",
            "description": "The maximum time in milliseconds to wait for a stream reader."
          },
          "multicast.addrMax": {
            "type": "string",
            "description": "The maximum multicast address."
          },
          "general.wait_add_track_ms": {
            "type": "string",
            "description": "The time in milliseconds to wait for adding a track."
          },
          "http.allow_cross_domains": {
            "type": "string",
            "description": "Whether to allow cross-domain requests for HTTP."
          },
          "protocol.modify_stamp": {
            "type": "string",
            "description": "Whether to modify the timestamp for the protocol."
          },
          "rtp.videoMtuSize": {
            "type": "string",
            "description": "The MTU size for video packets in RTP."
          },
          "api.snapRoot": {
            "type": "string",
            "description": "The root directory for snapshots in the API."
          },
          "protocol.enable_audio": {
            "type": "string",
            "description": "Whether to enable audio for the protocol."
          },
          "hook.on_server_keepalive": {
            "type": "string",
            "description": "The action to take when the server keeps alive."
          },
          "multicast.addrMin": {
            "type": "string",
            "description": "The minimum multicast address."
          },
          "protocol.ts_demand": {
            "type": "string",
            "description": "Whether to enable demand for TS."
          },
          "protocol.enable_fmp4": {
            "type": "string",
            "description": "Whether to enable FMP4 for the protocol."
          },
          "rtsp.lowLatency": {
            "type": "string",
            "description": "Whether to enable low latency for RTSP."
          },
          "http.allow_ip_range": {
            "type": "string",
            "description": "The IP range to allow for HTTP requests."
          },
          "hook.on_rtsp_realm": {
            "type": "string",
            "description": "The action to take when the RTSP realm is accessed in hooks."
          },
          "hook.on_stream_changed": {
            "type": "string",
            "description": "The action to take when a stream is changed in hooks."
          },
          "http.forwarded_ip_header": {
            "type": "string",
            "description": "The header to use for forwarded IP addresses in HTTP requests."
          },
          "rtp_proxy.h265_pt": {
            "type": "string",
            "description": "The H.265 payload type used by the RTP proxy."
          },
          "hook.on_del_mp4": {
            "type": "string",
            "description": "The action to take when an MP4 file is deleted in hooks."
          },
          "protocol.enable_hls": {
            "type": "string",
            "description": "Whether to enable HLS for the protocol."
          },
          "protocol.enable_mp4": {
            "type": "string",
            "description": "Whether to enable MP4 for the protocol."
          },
          "rtc.port": {
            "type": "string",
            "description": "The port used for RTC."
          },
          "protocol.fmp4_demand": {
            "type": "string",
            "description": "Whether to enable demand for FMP4."
          },
          "record.sampleMS": {
            "type": "string",
            "description": "The time in milliseconds for each sample during recording."
          },
          "shell.port": {
            "type": "string",
            "description": "The port used for the shell."
          },
          "hook.on_shell_login": {
            "type": "string",
            "description": "The action to take when logging in to the shell."
          },
          "cluster.retry_count": {
            "type": "string",
            "description": "The number of times to retry connecting to the cluster."
          },
          "general.enableVhost": {
            "type": "string",
            "description": "Whether to enable virtual hosts."
          },
          "general.unready_frame_cache": {
            "type": "string",
            "description": "The size of the unready frame cache."
          },
          "rtc.preferredCodecV": {
            "type": "string",
            "description": "The preferred video codec for RTC."
          },
          "rtp_proxy.h264_pt": {
            "type": "string",
            "description": "The H.264 payload type used by the RTP proxy."
          },
          "protocol.auto_close": {
            "type": "string",
            "description": "Whether to automatically close connections for the protocol."
          },
          "srt.latencyMul": {
            "type": "string",
            "description": "The latency multiplier for SRT."
          },
          "hook.on_server_exited": {
            "type": "string",
            "description": "The action to take when the server is exited."
          },
          "general.resetWhenRePlay": {
            "type": "string",
            "description": "Whether to reset when replaying."
          },
          "protocol.mp4_save_path": {
            "type": "string",
            "description": "The save path for MP4 files in the protocol."
          },
          "protocol.continue_push_ms": {
            "type": "string",
            "description": "The time in milliseconds for continuing to push data for the protocol."
          },
          "rtp_proxy.dumpDir": {
            "type": "string",
            "description": "The dump directory for the RTP proxy."
          },
          "rtp_proxy.ps_pt": {
            "type": "string",
            "description": "The payload type used for PS in the RTP proxy."
          },
          "hook.enable": {
            "type": "string",
            "description": "Whether to enable hooks."
          },
          "rtc.timeoutSec": {
            "type": "string",
            "description": "The timeout value for RTC in seconds."
          },
          "rtc.preferredCodecA": {
            "type": "string",
            "description": "The preferred audio codec for RTC."
          },
          "hls.segKeep": {
            "type": "string",
            "description": "The number of HLS segments to keep."
          },
          "multicast.udpTTL": {
            "type": "string",
            "description": "The TTL value for UDP multicast."
          },
          "rtp.h264_stap_a": {
            "type": "string",
            "description": "Whether to enable STAP-A for H.264 in RTP."
          },
          "hook.on_stream_none_reader": {
            "type": "string",
            "description": "The action to take when there are no stream readers in hooks."
          },
          "hook.on_record_ts": {
            "type": "string",
            "description": "The action to take when recording TS files in hooks."
          },
          "ffmpeg.bin": {
            "type": "string",
            "description": "The path to the FFmpeg binary."
          },
          "protocol.enable_ts": {
            "type": "string",
            "description": "Whether to enable demand for TS in the protocol."
          },
          "protocol.enable_hls_fmp4": {
            "type": "string",
            "description": "Whether to enable HLS FMP4 in the protocol."
          },
          "hls.segNum": {
            "type": "string",
            "description": "The number of HLS segments."
          },
          "http.maxReqSize": {
            "type": "string",
            "description": "The maximum size of requests for HTTP."
          },
          "rtc.tcpPort": {
            "type": "string",
            "description": "The TCP port used for RTC."
          },
          "cluster.timeout_sec": {
            "type": "string",
            "description": "The timeout value for the cluster in seconds."
          },
          "general.enable_ffmpeg_log": {
            "type": "string",
            "description": "Whether to enable FFmpeg logging."
          },
          "general.mediaServerId": {
            "type": "string",
            "description": "The ID of the media server."
          },
          "hook.on_http_access": {
            "type": "string",
            "description": "The action to take when accessing HTTP in hooks."
          },
          "general.wait_track_ready_ms": {
            "type": "string",
            "description": "The time in milliseconds to wait for a track to be ready."
          },
          "rtsp.authBasic": {
            "type": "string",
            "description": "Whether to enable basic authentication for RTSP."
          },
          "hook.on_rtsp_auth": {
            "type": "string",
            "description": "The action to take when authenticating RTSP in hooks."
          },
          "protocol.rtmp_demand": {
            "type": "string",
            "description": "Whether to enable demand for RTMP in the protocol."
          },
          "protocol.add_mute_audio": {
            "type": "string",
            "description": "Whether to add mute audio for the protocol."
          },
          "record.fileBufSize": {
            "type": "string",
            "description": "The buffer size for recording files."
          },
          "rtmp.keepAliveSecond": {
            "type": "string",
            "description": "The time in seconds to keep the RTMP connection alive."
          },
          "hook.on_play": {
            "type": "string",
            "description": "The action to take when playing a stream in hooks."
          }
        }
      }
    },
    "securitySchemes": {}
  },
  "servers": [],
  "security": []
}
